# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('group', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('leader', models.IntegerField(blank=True)),
                ('create_date', models.DateField(default=datetime.datetime(2017, 12, 13, 20, 57, 19, 378829, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2017, 12, 13, 20, 57, 19, 379568, tzinfo=utc))),
                ('text', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('chat', models.IntegerField()),
            ],
        ),
    ]
