# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20171215_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 22, 33, 12, 339547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 22, 33, 12, 340266, tzinfo=utc)),
        ),
    ]
