# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('deadline', models.IntegerField(blank=True)),
                ('create_date', models.DateField(default=datetime.datetime(2017, 12, 15, 23, 4, 17, 626043, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(default='')),
                ('create_date', models.DateField(default=datetime.datetime(2017, 12, 15, 23, 4, 17, 626574, tzinfo=utc))),
                ('deadline', models.DateField(null=True)),
                ('position', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('parent', models.IntegerField(blank=True)),
                ('has_child', models.BooleanField(default=False)),
                ('project', models.IntegerField(blank=True)),
            ],
        ),
    ]
